services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartcity
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: smartcity-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: C:/Users/rames/smart-city-frontend
    container_name: smartcity-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: